apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-ecr-secret-updater.name" }}-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.credentials.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.credentials.secretKey | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.aws.region }}
  NAMESPACES: {{ .Values.kubernetes.targetNamespaces | join "," | b64enc }}
  SECRET_NAME: {{ .Values.kubernetes.secretName | b64enc }}