apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "aws-secret-updater.fullname" . }}
  labels:
    {{- include "aws-secret-updater.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "aws-secret-updater.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "aws-secret-updater.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.awsCredentials.secretName }}
                      key: aws-access-key-id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.awsCredentials.secretName }}
                      key: aws-secret-access-key
                - name: AWS_REGION
                  value: {{ .Values.awsRegion }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
