name: Release Helm Charts
on:
  push:
    branches:
      - main
#    paths:
#      - aws-ecr-secret-updater/**

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  release:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CONNECT_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Packaging and merge index.yaml from S3
        env:
          DOCKER_USERNAME: ${{ vars.HELM_DOCKER_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HELM_DOCKER_REGISTRY_TOKEN }}
        run: |
          mkdir -p tgz
          helm package ./aws-ecr-secret-updater ./tgz
          echo "$DOCKER_PASSWORD" | helm registry login --username $DOCKER_USERNAME --password-stdin registry-1.docker.io
          
          FILENAME=$(ls ./tgz)
          helm push $FILENAME oci://registry-1.docker.io/koo04034
