name: Release Helm Charts
on:
  push:
    branches:
      - main
#    paths:
#      - aws-ecr-secret-updater/**

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  release:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.1

      - name: Packaging and merge index.yaml from S3
        env:
          DOCKER_USERNAME: ${{ vars.HELM_DOCKER_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HELM_DOCKER_REGISTRY_TOKEN }}
        run: |
          mkdir -p ./tgz
          ls -alh
          pwd
          helm package ./aws-ecr-secret-updater ./tgz
          echo "$DOCKER_PASSWORD" | helm registry login --username $DOCKER_USERNAME --password-stdin registry-1.docker.io
          
          FILENAME=$(ls ./tgz)
          helm push $FILENAME oci://registry-1.docker.io/koo04034
