name: Release Helm Charts
on:
  push:
    branches:
      - main
#    paths:
#      - aws-ecr-secret-updater/**

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  release:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CONNECT_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Packaging and merge index.yaml from S3
        run: |
          mkdir -p docs
          helm package ./aws-ecr-secret-updater -d ./docs
          aws s3api get-object --bucket lutergs-helm-release --key index.yaml ./before-index.yaml
          helm repo index ./docs --url https://lutergs-helm-release.s3.ap-northeast-2.amazonaws.com/aws-ecr-secret-updater/ --merge ./before-index.yaml
          mv ./docs/index.yaml ./index.yaml
          aws s3 cp ./docs s3://lutergs-helm-release/aws-ecr-secret-updater/ --acl public-read
          aws s3api put-object --bucket lutergs-helm-release --key index.yaml --body ./index.yaml
